version: '3.8'

services:
  # CIRIS Agent
  ciris-agent:
    build:
      context: .
      dockerfile: docker/agent/Dockerfile
    container_name: ciris-agent-datum
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - CIRIS_AGENT_NAME=Datum
      - CIRIS_AGENT_ID=datum
      - CIRIS_PORT=8080
      - CIRIS_ADAPTER=api
      - CIRIS_ADAPTER_DISCORD=discord
      - CIRIS_MOCK_LLM=true
      - CIRIS_API_HOST=0.0.0.0
      - CIRIS_API_PORT=8080
      - CIRIS_API_INTERACTION_TIMEOUT=55.0
      # Discord configuration - these will be loaded from .env file if present
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - DISCORD_CHANNEL_IDS=${DISCORD_CHANNEL_IDS}
      - DISCORD_DEFERRAL_CHANNEL_ID=${DISCORD_DEFERRAL_CHANNEL_ID}
      - WA_USER_ID=${WA_USER_ID}
      - SNORE_CHANNEL_ID=${SNORE_CHANNEL_ID}
    volumes:
      - agent_data:/app/data
      - agent_logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - ciris-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: ["python", "main.py", "--adapter", "api", "--adapter", "discord", "--mock-llm"]

  # GUI Application
  ciris-gui:
    build:
      context: ./CIRISGUI
      dockerfile: docker/Dockerfile.agui
    container_name: ciris-gui-local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CIRIS_API_URL=http://ciris-agent-local:8080
      - NEXT_PUBLIC_MANAGER_URL=http://host.docker.internal:8888
    networks:
      - ciris-network
    depends_on:
      - ciris-agent
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # Nginx Reverse Proxy
  ciris-nginx:
    image: nginx:alpine
    container_name: ciris-nginx-local
    ports:
      - "80:80"
    volumes:
      # Mount nginx config directory - CIRISManager will write nginx.conf here
      - /home/emoore/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount logs directory
      - nginx_logs:/var/log/nginx
    networks:
      - ciris-network
    depends_on:
      - ciris-agent
      - ciris-gui
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  # CIRISManager API (non-containerized, runs on host)
  # Note: Run this separately with: python deployment/run-ciris-manager-api.py

volumes:
  agent_data:
  agent_logs:
  nginx_logs:

networks:
  ciris-network:
    driver: bridge