"""Central constants for CIRIS."""
from pathlib import Path

# Agent defaults
DEFAULT_WA = "CIRIS"
DEFAULT_TEMPLATE = "default"
DEFAULT_TEMPLATE_PATH = Path("ciris_templates")

# Model defaults  
DEFAULT_OPENAI_MODEL_NAME = "gpt-4o-mini"
DEFAULT_LLM_ENDPOINT = "https://api.openai.com/v1"
DEFAULT_LLM_TIMEOUT = 30
DEFAULT_LLM_MAX_RETRIES = 3

# Prompt defaults
DEFAULT_PROMPT_TEMPLATE = "default_prompt"

# Time defaults
DEFAULT_CONSOLIDATION_INTERVAL_HOURS = 6
DEFAULT_RETENTION_HOURS = 24 * 7  # 1 week

# System defaults
DEFAULT_MAX_THOUGHT_DEPTH = 5
DEFAULT_ROUND_DELAY_SECONDS = 0.2
DEFAULT_NUM_ROUNDS = 10
DEFAULT_TASK_TIMEOUT = 300  # 5 minutes
DEFAULT_THOUGHT_TIMEOUT = 60  # 1 minute

# Database defaults
DEFAULT_DB_PATH = "ciris_engine.db"
DEFAULT_DB_TIMEOUT = 30.0

# API defaults
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8080
DEFAULT_API_INTERACTION_TIMEOUT = 30.0

# Discord defaults
DEFAULT_DISCORD_RATE_LIMIT_MESSAGES = 5
DEFAULT_DISCORD_RATE_LIMIT_WINDOW = 60  # seconds

# Memory defaults
DEFAULT_MEMORY_LIMIT_MB = 1024
DEFAULT_THOUGHT_HISTORY_LIMIT = 100

# Correlation defaults
DEFAULT_CORRELATION_RETENTION_DAYS = 30
DEFAULT_CORRELATION_MAX_ENTRIES = 10000